### ISSUE TITLE
Errors when opening the project on Unity version 2019.4.1

### ISSUE THREAD

**Issue by Hisaack** [googlesamples/arcore-depth-lab#37]
Hi, I have downloaded the repo and imported ARCore Unity SDK into the project and all the dependencies including Multiplayer HLAPI 1.0.8, and XR Legacy Input Helpers 2.1.7. Here is the screenshot attached below.
![Screenshot (642)](https://user-images.githubusercontent.com/40029080/123693054-3c983480-d860-11eb-9c59-a463b72d7f09.png)

**Comment by ruofeidu** [comment]
Hi Hisaack, sorry for the late reply due to vacations. I have personally tried both branches on Windows and Mac in Unity 2019.4 and 2020.3 respectively for the two branches and both builds work for me.

From the log, I think XR Legacy Input Helpers is not loaded... Which OS are you using? If you are trying out the arcore_legacy_sdk branch, would you like to use Unity 2019.4.22f or above but starting with 2019.4? Thank you so much!

**Comment by ruofeidu** [comment]
Let me know if you have further error that I could help.
